EInvoice.Web/Controllers/CompanyInfoController.cs
using AutoMapper;
using Data.Utilities.Enumeration;
using EInvoice.Data.Data;
using EInvoice.Data.Services;
using EInvoice.Data.Utilities;
using EInvoice.Web.Models;
using System;
using System.Linq;
using System.Web.Mvc;

namespace EInvoice.Web.Controllers
{
    [Auth(Enumerations.Role.Accountant)]
    public class CompanyInfoController : Controller
    {
        private readonly ICompanyService _companyService;

        public CompanyInfoController(ICompanyService companyService)
        {
            _companyService = companyService;
        }

        public ActionResult Index()
        {
            var model = Mapper.Map<CompanyViewModel>(_companyService.GetAll().First());
            return View(model);
        }

        [HttpPost]
        public ActionResult Update(Company company)
        {
            try
            {
                _companyService.UpdateCompany(company);
            }
            catch (Exception e)
            {
                ViewData["EditError"] = e.Message;
            }

            return RedirectToAction("Index");
        }
    }
}

EInvoice.Web/Views/CompanyInfo/Index.cshtml
@model EInvoice.Web.Models.CompanyViewModel
@{
    ViewBag.Title = "Company Information";
    Layout = "~/Views/Shared/_mainLayout.cshtml";
}
<style>
    .field-validation-error{
        color:red
    }

    input[type=file]{
        color:transparent;
    }

</style>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2 style="font-size: 27px">Company Information</h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class="row">
                    <!-- left column -->
                    <div class="col-md-4 col-sm-6 col-xs-12">
                        <div class="text-center">
                            <img src="~/Assets/Owner/Images/Enlab logo.png" class="img-circle img-thumbnail" alt="avatar" />

                            <input style="visibility: hidden" type="file" id="file" class="text-center center-block well well-sm" value="Change logo">
                            <button style="margin-top: -20%;" id="files" class="btn btn-primary" onclick="document.getElementById('file').click(); return false;">Change logo</button>

                        </div>
                    </div>
                    <!-- edit form column -->
                    <div class="col-md-8 col-sm-6 col-xs-12 personal-info">
                        @using (Ajax.BeginForm("Update", "CompanyInfo",
                           null,
                           new AjaxOptions() { HttpMethod = "post", OnSuccess = "SubmitCompanyStatus()" },
                           new { @class = "form", @id = "registrationForm" }))
                        {
                            <div class="form-group">
                                <div class="col-xs-12">
                                    <label><h4>Company Name</h4></label>
                                    @Html.TextBoxFor(model => model.Name,
                                        new
                                        {
                                            type = "text",
                                            @class = "form-control",
                                            @readonly = "readonly",
                                            id = "companyName"
                                        })
                                    @Html.ValidationMessageFor(model => model.Name)
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-xs-6">
                                    <label><h4>Tax Code</h4></label>
                                    @Html.TextBoxFor(model => model.TaxCode,
                                        new
                                        {
                                            type = "text",
                                            @class = "form-control",
                                            @readonly = "readonly",
                                            id = "taxCode"
                                        })
                                    @Html.ValidationMessageFor(model => model.TaxCode)
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-xs-6">
                                    <label><h4>Email</h4></label>
                                    @Html.TextBoxFor(model => model.Email,
                                        new
                                        {
                                            type = "text",
                                            @class = "form-control",
                                            @readonly = "readonly"
                                        })
                                    @Html.ValidationMessageFor(model => model.Email)
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-xs-12">
                                    <label><h4>Address</h4></label>
                                    @Html.TextBoxFor(model => model.Address,
                                        new
                                        {
                                            type = "text",
                                            @class = "form-control",
                                            @readonly = "readonly"
                                        })
                                    @Html.ValidationMessageFor(model => model.Address)
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-xs-6">
                                    <label><h4>Phone</h4></label>
                                    @Html.TextBoxFor(model => model.Phone,
                                        new
                                        {
                                            type = "text",
                                            @class = "form-control",
                                            @readonly = "readonly"
                                        })
                                    @Html.ValidationMessageFor(model => model.Phone)
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-xs-6">
                                    <label><h4>Fax</h4></label>
                                    @Html.TextBoxFor(model => model.Fax,
                                        new
                                        {
                                            type = "text",
                                            @class = "form-control",
                                            @readonly = "readonly"
                                        })
                                    @Html.ValidationMessageFor(model => model.Fax)
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-xs-6">
                                    <label><h4>Legal Representative</h4></label>
                                    @Html.TextBoxFor(model => model.LegalPresenter,
                                        new
                                        {
                                            type = "text",
                                            @class = "form-control",
                                            @readonly = "readonly"
                                        })
                                    @Html.ValidationMessageFor(model => model.LegalPresenter)
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-xs-6">
                                    <label><h4>Website</h4></label>
                                    @Html.TextBoxFor(model => model.Website,
                                        new
                                        {
                                            type = "text",
                                            @class = "form-control",
                                            @readonly = "readonly"
                                        })
                                    @Html.ValidationMessageFor(model => model.Website)
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-xs-6">
                                    <label><h4>Bank ID</h4></label>
                                    @Html.TextBoxFor(model => model.BankAccountID,
                                        new
                                        {
                                            type = "text",
                                            @class = "form-control",
                                            @readonly = "readonly"
                                        })
                                    @Html.ValidationMessageFor(model => model.BankAccountID)
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-xs-6">
                                    <label><h4>Bank Name</h4></label>
                                    @Html.TextBoxFor(model => model.BankName,
                                        new
                                        {
                                            type = "text",
                                            @class = "form-control",
                                            @readonly = "readonly"
                                        })
                                    @Html.ValidationMessageFor(model => model.BankName)
                                </div>
                            </div>
                            <div class="form-group" style="float:right">
                                <div class="col-xs-12">
                                    <br>
                                    <button id="submitCompany" style="visibility: hidden" type="submit" class="btn btn-lg btn-success"><i class="glyphicon glyphicon-ok-sign"></i> Save</button>
                                    <button id="editCompany" onclick="EditCompany()" type="button" class="btn btn-lg"><i class="glyphicon glyphicon-edit"></i>Edit</button>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="~/Assets/Owner/js/company-edit.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>